export const data = {
  HistoryItems: [
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Distribution issue',
        ClaimCategoryId: 3,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 601083,
        ClaimDate: 'Nov 11, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=601083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Invoice issue',
        ClaimCategoryId: 4,
        StatusName: 'Created',
        StatusId: 1,
        ClaimNo: 600083,
        ClaimDate: 'Nov 11, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=600083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Distribution issue',
        ClaimCategoryId: 3,
        StatusName: 'Created',
        StatusId: 2,
        ClaimNo: 502083,
        ClaimDate: 'Sep 18, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=502083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Invoice issue',
        ClaimCategoryId: 4,
        StatusName: 'Created',
        StatusId: 3,
        ClaimNo: 501083,
        ClaimDate: 'Sep 18, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=501083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Invoice issue',
        ClaimCategoryId: 4,
        StatusName: 'Created',
        StatusId: 1,
        ClaimNo: 500083,
        ClaimDate: 'Sep 18, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=500083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Distribution issue',
        ClaimCategoryId: 3,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 408083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=408083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Distribution issue',
        ClaimCategoryId: 3,
        StatusName: 'Created',
        StatusId: 2,
        ClaimNo: 407083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=407083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Approved',
        StatusId: 3,
        ClaimNo: 406083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=406083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Distribution issue',
        ClaimCategoryId: 3,
        StatusName: 'Rejected',
        StatusId: 4,
        ClaimNo: 405083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=405083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Invoice issue',
        ClaimCategoryId: 4,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 404083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=404083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 403083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=403083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 402083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=402083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 401083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=401083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 400083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=400083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 300083,
        ClaimDate: 'Sep 17, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=300083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 200083,
        ClaimDate: 'Aug 19, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=200083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Return / exchange / missing',
        ClaimCategoryId: 2,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 100083,
        ClaimDate: 'Aug 14, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=100083',
      },
    },
    {
      Customer: {
        IsGuarantee: true,
        CustomerId: 300000,
        CustomerInitials: 'fl',
        ConsultantNumber: '1',
        ConsultantProfilePictureUrl:
          '/system/media/ProfilePhoto/Get?documentId=46700083&customerId=300000&key=544e578b207a4953fe8562bb8dec48e73d6550989f0169b5af14e148dbbd20ca',
        ConsultantTitle: 'Consultant',
        CustomerCategory: 'Consultant',
        DisplayName: 'first_name_1 last_name_1',
        Email: 'test1@oriflame.test',
        FirstName: 'first_name_1',
        LastName: 'last_name_1',
        PhoneNo: null,
        ClaimCustomerType: 1,
      },
      Claim: {
        ClaimCategoryName: 'Invoice issue',
        ClaimCategoryId: 4,
        StatusName: 'Created',
        StatusId: 0,
        ClaimNo: 1083,
        ClaimDate: 'Jul 27, 2020',
        OriflamePublicComment: null,
        ClaimDetailUrl: '/mypages/order/claims/detail-consultant?claimId=1083',
      },
    },
  ],
  HasNextPage: false,
};

export const viewModel = {
  Branches: [
    { Id: 0, Name: 'Branch 1' },
    { Id: 1, Name: 'Branch 2' },
    { Id: 2, Name: 'Branch 3' },
    { Id: 3, Name: 'Branch 4' },
    { Id: 4, Name: 'Branch 5' },
    { Id: 5, Name: 'Branch 6' },
  ],
  Warehouses: [
    { Id: 0, Name: 'Warehouse 1' },
    { Id: 1, Name: 'Warehouse 2' },
    { Id: 2, Name: 'Warehouse 3' },
  ],
  ClaimStatuses: [
    { Id: 0, Name: 'Created' },
    { Id: 1, Name: 'Processing' },
    { Id: 2, Name: 'Partially approved' },
    { Id: 3, Name: 'Approved' },
    { Id: 4, Name: 'Denied' },
    { Id: 5, Name: 'Finished' },
  ],
};
